services:
  frontend:
    build:
      context: ./techpack_ops_frontend
      dockerfile: Dockerfile
    container_name: techpack_ops_frontend
    ports:
      - "3000:5173"
    volumes:
      - ./techpack_ops_frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - techpack_network
  backend:
    build:
      context: ./techpack_ops_backend
      dockerfile: Dockerfile
    container_name: techpack_ops_backend
    ports:
      - '8000:8000'
    volumes:
      - ./techpack_ops_backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app/api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - techpack_network
networks:
  techpack_network:
    driver: bridge
